[project]
name = "sales-prediction-using-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "sreeshanth", email = "sreeshanthkprakash@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.3.0",
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "scikit-learn>=1.9.1",
    "seaborn>=0.13.2",
]

[project.scripts]
sales-prediction-using-python = "sales_prediction_using_python:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
